# Generated by Django 4.0.6 on 2022-08-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlipInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentInfo', models.JSONField()),
                ('FiscalTerminalInfo', models.JSONField()),
                ('FolioInfo', models.JSONField()),
                ('HotelInfo', models.JSONField()),
                ('ReservationInfo', models.JSONField()),
                ('FiscalFolioUserInfo', models.JSONField()),
                ('BusinessDate', models.DateField(blank=True, null=True)),
                ('BusinessDateTime', models.DateTimeField(blank=True, null=True)),
                ('EinvoiceNumber', models.CharField(blank=True, default=' ', max_length=500, null=True)),
                ('EinvoiceType', models.CharField(blank=True, default='9: Not Upload', max_length=200, null=True)),
                ('EinvoiceStatus', models.CharField(blank=True, default='9: Not Upload', max_length=200, null=True)),
                ('EinvoiceFKey', models.CharField(default=' ', max_length=200)),
                ('EinvoicePattern', models.CharField(default=' ', max_length=200)),
                ('EinvoiceSerial', models.CharField(default=' ', max_length=200)),
                ('AuthorizedTaxCode', models.CharField(blank=True, default=' ', max_length=500, null=True)),
                ('EinvoiceAdjustDateTime', models.DateTimeField(blank=True, null=True)),
                ('EinvoiceIssueDateTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
