# Generated by Django 4.0.6 on 2022-08-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipinfo',
            name='FolioNo',
            field=models.IntegerField(default=0),
        ),
    ]
