# Generated by Django 4.0.6 on 2022-10-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opera', '0002_flipinfo_foliono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipinfo',
            name='FolioNo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
