# Generated by Django 4.1.5 on 2023-05-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opera', '0004_flipinfo_netamount_alter_flipinfo_foliono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipinfo',
            name='EinvoiceSerial',
            field=models.CharField(default='C23MAB', max_length=200),
        ),
    ]
